package control;

import java.util.ArrayList;
import java.util.List;

/**
 * This class is the data type for cards. The static function generateAllCards()
 * returns the set of all available cards in the game. All Card instances should
 * be generated by this function (note the private constructor).
 * 
 * @see #generateAllCards()
 */
public class Card {
	private int id;
	private String name;
	private Kind kind;
	
	/**
	 * Private constructor! Cards should be generated one time by Card.
	 * generateAllCards() and then maintained in appropriate data structures.
	 * 
	 * @param id unique id
	 * @param name
	 */
	private Card(int id, String name, Kind kind) {
		this.name = name;
		this.id = id;
		this.kind = kind;
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @return the kind
	 */
	public Kind getKind() {
		return kind;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return 61 + id;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Card)) {
			return false;
		}
		return id == ((Card) obj).id;
	}
	
	/**
	 * Static method for generating the card deck. It is returned as list to
	 * make shuffling easier. Use this method for generating cards instead of
	 * the constructor. 
	 */
	public static List<Card> generateAllCards() {
		String[] persons = {"Professor Plum", "Miss Scarlett", "Colonel Mustard", "Mrs. White",
				"Reverend Green", "Mrs. Peacock"};
		String[] weapons = {"Candlestick", "Dagger", "Lead Piping", "Revolver",
				"Rope", "Spanner"};
		String[] rooms = {"Hall", "Lounge", "Dining Room", "Kitchen", "Ballroom", "Conservatory", 
				"Billiard Room", "Library", "Study"};
		int id = 0;
		List<Card> cards = new ArrayList<Card>();
		for (String person : persons) {
			cards.add(new Card(id++, person, Kind.PERSON));
		}
		for (String weapon : weapons) {
			cards.add(new Card(id++, weapon, Kind.WEAPON));
		}
		for (String room : rooms) {
			cards.add(new Card(id++, room, Kind.ROOM));
		}
		return cards;
	}
}
